**#NumPy Boolean Masking and Matplotlib Subplots**

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [10]:
matrix = np.arange(1, 17).reshape(4,4)

print("Matrix:\n", matrix)

result = matrix[(matrix > 10) & (matrix % 2 == 0)]

print("\nElements greater than 10 and divisible by 2: ", result)

Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Elements greater than 10 and divisible by 2:  [12 14 16]


In [ ]:
epochs = [1, 2, 3, 4, 5]
accuracy = [55, 72, 83, 89, 94]

hardware = ['CPU', 'GPU', 'EDGE TPU']
fps = [60, 120, 250]

fix.ax = plt.subplots(1, 2, figsize=(10, 4))

ax[0].plot(
    epochs,
    accuracy,
    color = 'blue',
    marker ='o',
    linspace = 2
)
ax[0].set_title = ("Training Accuracy")
ax[0].set_xlabel = ("Epochs")
ax[0].set_ylabel = ("Accuracy")
ax[0].grid(True)

colors = ["red", "green", "orange"]

ax[1].bar(
    hardware,
    fps, 
    color= colors
)
ax[1].set_title = ("Inference Speed")
ax[0].set_xlabel = ("Epochs")
ax[0].set_ylabel = ("Accuracy")

plt.tight_layout
plt.show()
